### ISSUE TITLE
"error: wnn/VgRamNeuron.h: No such file or directory" compiling module traffic_light

### ISSUE THREAD

**Issue by xperroni** [LCAD-UFES/carmen_lcad#3]
**Steps to reproduce:**

```
cd src/traffic_light
make clean
make
```

**Notes:**

I looked around but couldn't find the `wnn` folder, much less the `VgRamNeuron.h` file. Is this from a new library not previously used in CARMEN?

I don't particularly need `traffic_light` to compile right now, but since it's included in the global Makefile I thought it important to report this.

**Comment by filipemtz** [comment]
The traffic light module is still in development. The include is from an external library, but I'm not sure if the final version of the module will in fact use the lib. I will remove the program that uses the lib from the traffic light's makefile right now as a workaround. As soon as the module become more stable, I send instructions about how to install the lib.

**Comment by xperroni** [comment]
Fixed by installing new dependency libwnn.
